#application: linen-tracer-682
#version: 1
runtime: python27
#runtime: python3
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: root.app
  
- url: /loc
  static_dir: ../math/src/site/algorithms

- url: /tale/.*
  script: root.app

- url: /static
  static_dir: static
  
- url: /main
  static_dir: main
      
- url: /reveal.js
  static_dir: reveal.js
  
- url: /reveal.js.40
  static_dir: reveal.js.40

- url: /downloads
  static_dir: downloads

- url: /data-js
  static_dir: data-js

- url: /default/.*
  script: default.app


- url: /algorithms/.*
  script: algorithms.app

- url: /algorithms-bin
  static_dir: algorithms-bin

- url: /algorithms-tales
  static_dir: algorithms-tales
  
- url: /numtheory/.*
  script: numtheory.app
  
- url: /numtheory-bin
  static_dir: numtheory-bin

- url: /numtheory-exams
  static_dir: numtheory-exams


- url: /numtheory-tales
  static_dir: numtheory-tales

- url: /visualizations/.*
  script: visualizations.app
  
- url: /visualizations-bin
  static_dir: visualizations-bin

- url: /visualizations-tales
  static_dir: visualizations-tales

- url: /rbs/.*
  script: rbs.app
  
- url: /rbs-bin
  static_dir: rbs-bin

- url: /rbs-tales
  static_dir: rbs-tales

- url: /semantic/.*
  script: semantic.app
  
- url: /semantic-bin
  static_dir: semantic-bin

- url: /semantic-tales
  static_dir: semantic-tales

- url: /discrete/.*
  script: discrete.app
  
- url: /discrete-bin
  static_dir: discrete-bin
  
- url: /discrete-tales
  static_dir: discrete-tales

- url: /discrete2021/.*
  script: discrete2021.app
  
- url: /discrete2021-bin
  static_dir: discrete2021-bin
  
- url: /discrete2021-tales
  static_dir: discrete-tales


- url: /discrete2022/.*
  script: discrete2022.app

- url: /discrete2022-bin
  static_dir: discrete2022-bin



- url: /data-structures/.*
  script: data_structures.app

- url: /data-structures-assignments
  static_dir: data-structures-assignments
    
- url: /data-structures-bin
  static_dir: data-structures-bin

- url: /data-structures-tales
  static_dir: data-structures-tales



- url: /style
  static_dir: style

- url: /problembase/index.html
  script: problembase-index.app

- url: /problembase/problems.html
  script: problembase-problems.app

- url: /problembase/tasks.html
  script: problembase-tasks.app

- url: /problembase/reports.html
  script: problembase-reports.app

- url: /problembase/reports-concepts.html
  script: problembase-reports-concepts.app
  
- url: /problembase/reports-concepts/(.*)
  script: problembase-reports-concepts.app
  

- url: /problembase/reports-qtypes.html
  script: problembase-reports-qtypes.app

- url: /problembase/reports-taskgroups.html
  script: problembase-reports-taskgroups.app

- url: /problembase/references.html
  script: problembase-references.app


- url: /problembase-bin
  static_dir: problembase-bin

- url: /problembase-tales
  static_dir: problembase-tales


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest

  
