application: linen-tracer-682
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: root.app

- url: /static
  static_dir: static
  
- url: /main
  static_dir: main
  
- url: /prob/index\.html
  script: prob_index.app

- url: /prob/tasks\.html
  script: prob_tasks.app

- url: /prob/task_groups\.html
  script: prob_task_groups.app
  
- url: /concept/(.*)
  script: prob_get_concept.app
  
- url: /files-exam
  static_dir: files-exam
  
- url: /files-misc
  static_dir: files-misc
 
- url: /files-prob
  static_dir: files-prob
  
- url: /files-tale
  static_dir: files-tale
  
- url: /reveal.js
  static_dir: reveal.js
  
- url: /analysis/.*
  script: analysis.app
  
- url: /exam/.*
  script: exam.app
  
- url: /tale/.*
  script: tale.app
  
- url: /downloads
  static_dir: downloads

- url: /charts
  static_dir: charts

- url: /data-js
  static_dir: data-js

- url: /default/.*
  script: default.app


- url: /algorithms/.*
  script: algorithms.app

- url: /algorithms-bin
  static_dir: algorithms-bin

- url: /algorithms-tales
  static_dir: algorithms-tales
  
- url: /numtheory/.*
  script: numtheory.app
  
- url: /numtheory-bin
  static_dir: numtheory-bin

- url: /numtheory-tales
  static_dir: numtheory-tales

- url: /visualizations/.*
  script: visualizations.app
  
- url: /visualizations-bin
  static_dir: visualizations-bin

- url: /visualizations-tales
  static_dir: visualizations-tales

- url: /style
  static_dir: style

- url: /problembase/problems.html
  script: problembase-problems.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest